name: example
description: Example
version: 1.0.0+1
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  cupertino_icons:
  disposable_provider:
  flutter:
    sdk: flutter
  provider:
  vsync_provider:
    path: ..
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
