name: vsync_provider
description: VsyncProvider provides vsync for AnimationController. This works with provider package.
version: 0.4.0
homepage: https://github.com/mono0926/vsync_provider
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: